#![allow(unused)]

use crate::core::git::GitInfo;
use crate::core::paths::project_log_dir;
use anyhow::Result;
use chrono::Local;
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::PathBuf;

/// Error context for logging
#[derive(Debug, Clone)]
pub struct ErrorContext {
    pub current_dir: String,
    pub git_branch: Option<String>,
    pub git_state: Option<String>,
}

/// Collect current error context
pub fn collect_error_context() -> ErrorContext {
    let current_dir = std::env::current_dir()
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|_| "unknown".to_string());

    let git_branch = GitInfo::current_branch().ok();

    let git_state = if GitInfo::has_merge_in_progress() {
        Some("MERGE_IN_PROGRESS".to_string())
    } else if GitInfo::has_rebase_in_progress() {
        Some("REBASE_IN_PROGRESS".to_string())
    } else if GitInfo::conflicted_files()
        .map(|f| !f.is_empty())
        .unwrap_or(false)
    {
        Some("CONFLICTS".to_string())
    } else {
        Some("Clean".to_string())
    };

    ErrorContext {
        current_dir,
        git_branch,
        git_state,
    }
}

/// Get error log path - prefer .openzed-git/gitlogerror.md in project, fallback to global
pub fn error_log_path() -> Result<PathBuf> {
    let log_dir = project_log_dir();

    // Ensure directory exists
    if !log_dir.exists() {
        fs::create_dir_all(&log_dir)?;
    }

    Ok(log_dir.join("gitlogerror.md"))
}

/// Initialize the error log file if it doesn't exist
pub fn init_error_log() -> Result<()> {
    let path = error_log_path()?;

    if !path.exists() {
        let header = "# OpenZed Git Error Log\n\nThis file is automatically generated by OpenZed Git.\n\n---\n\n";
        fs::write(&path, header)?;
    }

    Ok(())
}

/// Append error to the log file
pub fn append_error_log(
    command: &str,
    error_type: &str,
    title: &str,
    message: &str,
    raw_error: &str,
    suggested_fix: Option<&str>,
    context: &ErrorContext,
) -> Result<PathBuf> {
    let path = error_log_path()?;

    // Ensure log file exists
    init_error_log()?;

    let timestamp = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();

    let mut log_entry = format!(
        r#"## {}

| Field | Value |
|---|---|
| Command | `{}` |
| Error Type | {} |
| Title | {} |
| Suggested Fix | `{}` |

### Message

```text
{}
```

### Raw Error

```text
{}
```

### Context

```text
Current directory: {}
Git branch: {}
Git state: {}
```

---

"#,
        timestamp,
        command,
        error_type,
        title,
        suggested_fix.unwrap_or("None"),
        message,
        raw_error,
        context.current_dir,
        context.git_branch.as_deref().unwrap_or("None"),
        context.git_state.as_deref().unwrap_or("None"),
    );

    // Append to file
    let mut file = OpenOptions::new().create(true).append(true).open(&path)?;

    file.write_all(log_entry.as_bytes())?;

    Ok(path)
}

/// Format error for display (extract key message)
pub fn format_error_message(raw: &str) -> String {
    // Try to extract meaningful part
    let cleaned = raw
        .lines()
        .filter(|line| !line.is_empty())
        .take(3)
        .collect::<Vec<_>>()
        .join(" ");

    if cleaned.len() > 200 {
        cleaned[..200].to_string() + "..."
    } else {
        cleaned
    }
}
